<?xml version="1.0" encoding='ISO-8859-1' standalone='yes' ?>
<TestRun>
  <FailedTests>
    <FailedTest id="2">
      <Name>Test::testFailure</Name>
      <FailureType>Assertion</FailureType>
      <Location>
        <File>cppunit.cpp</File>
        <Line>34</Line>
      </Location>
      <Message>assertion failed
- Expression: 1 == 2
</Message>
    </FailedTest>
    <FailedTest id="3">
      <Name>Test::testThrow</Name>
      <FailureType>Error</FailureType>
      <Message>uncaught exception of type std::exception
- St9exception
</Message>
    </FailedTest>
    <FailedTest id="5">
      <Name>Test::testDidntThrow</Name>
      <FailureType>Assertion</FailureType>
      <Message>expected exception not thrown
- Expected exception type: std::exception
</Message>
    </FailedTest>
  </FailedTests>
  <SuccessfulTests>
    <Test id="1">
      <Name>Test::testHelloWorld</Name>
    </Test>
    <Test id="4">
      <Name>Test::testExpectedThrow</Name>
    </Test>
    <Test id="6">
      <Name>Test::testExpectedFailure</Name>
    </Test>
    <Test id="7">
      <Name>AnotherTest::testIt</Name>
    </Test>
  </SuccessfulTests>
  <Statistics>
    <Tests>7</Tests>
    <FailuresTotal>3</FailuresTotal>
    <Errors>1</Errors>
    <Failures>2</Failures>
  </Statistics>
</TestRun>
